common:
  error:
    service-key: REPORT_MS
spring:
  application:
    name: report-service
  messages:
    basename: messages
service:
  order:
    url: ${ORDER_SERVICE_URL:http://localhost:8107}
  menu:
    url: ${MENU_SERVICE_URL:http://localhost:8105}
  user:
    url: ${USER_SERVICE_URL:http://localhost:8103}

server:
  port: ${REPORT_SERVER_PORT:8113}
  servlet:
    context-path: /api/report-ms
logging:
  level:
    az.flowix.report: DEBUG


security:
  internal-auth:
    secret: ${INTERNAL_AUTH_SECRET:}
