common:
  error:
    service-key: CUSTOMER_MS

spring:
  application:
    name: customer-service

  messages:
    basename: messages

service:
  menu:
    url: ${MENU_SERVICE_URL:http://localhost:8105}
  table:
    url: ${TABLE_SERVICE_URL:http://localhost:8106}
  order:
    url: ${ORDER_SERVICE_URL:http://localhost:8107}
  setting:
    url: ${SETTING_SERVICE_URL:http://localhost:8111}

server:
  port: ${CUSTOMER_SERVER_PORT:8110}
  servlet:
    context-path: /api/customer-ms

logging:
  level:
    az.codlab.customer: DEBUG


security:
  internal-auth:
    secret: ${INTERNAL_AUTH_SECRET:}
