common:
  error:
    service-key: ROLE_MS

spring:
  application:
    name: role-service

  datasource:
    url: ${ROLE_DB_URL:jdbc:postgresql://localhost:5432/tabler?currentSchema=tabler_role}
    username: ${ROLE_DB_USERNAME:postgres}
    password: ${ROLE_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:validate}
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  messages:
    basename: messages,i18n/messages

server:
  port: ${ROLE_SERVER_PORT:8104}
  servlet:
    context-path: /api/role-ms

service:
  user:
    url: ${USER_SERVICE_URL:http://localhost:8103}

logging:
  level:
    az.codlab.role: DEBUG
