common:
  error:
    service-key: KITCHEN_MS

spring:
  application:
    name: kitchen-service

  messages:
    basename: messages

service:
  order:
    url: ${ORDER_SERVICE_URL:http://localhost:8107}

server:
  port: ${KITCHEN_SERVER_PORT:8108}
  servlet:
    context-path: /api/kitchen-ms

logging:
  level:
    az.codlab.kitchen: DEBUG


security:
  internal-auth:
    secret: ${INTERNAL_AUTH_SECRET:}
