common:
  error:
    service-key: ORDER_MS

spring:
  application:
    name: order-service

  datasource:
    url: ${ORDER_DB_URL:jdbc:postgresql://localhost:5432/resto?currentSchema=resto_order}
    username: ${ORDER_DB_USERNAME:postgres}
    password: ${ORDER_DB_PASSWORD:mysecretpassword}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:validate}
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  messages:
    basename: messages,i18n/messages

server:
  port: ${ORDER_SERVER_PORT:8107}
  servlet:
    context-path: /api/order-ms

service:
  table:
    url: ${TABLE_SERVICE_URL:http://localhost:8106}
  menu:
    url: ${MENU_SERVICE_URL:http://localhost:8105}
  setting:
    url: ${SETTING_SERVICE_URL:http://localhost:8111}

logging:
  level:
    az.flowix.order: DEBUG

feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 5000
        loggerLevel: BASIC

security:
  internal-auth:
    secret: ${INTERNAL_AUTH_SECRET}
