common:
  error:
    service-key: ORG

spring:
  application:
    name: organization-service

  datasource:
    url: ${ORG_DB_URL:jdbc:postgresql://localhost:5432/tabler_organization}
    username: ${ORG_DB_USERNAME:postgres}
    password: ${ORG_DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:validate}
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  messages:
    basename: messages

service:
  role:
    url: ${ROLE_SERVICE_URL:http://localhost:8104}
  user:
    url: ${USER_SERVICE_URL:http://localhost:8103}
  setting:
    url: ${SETTING_SERVICE_URL:http://localhost:8111}
  table:
    url: ${TABLE_SERVICE_URL:http://localhost:8106}
  order:
    url: ${ORDER_SERVICE_URL:http://localhost:8107}

server:
  port: ${ORG_SERVER_PORT:8102}
  servlet:
    context-path: /api/organization-ms

logging:
  level:
    az.codlab.organization: DEBUG
