common:
  error:
    service-key: SETTING_MS

spring:
  application:
    name: setting-service

  datasource:
    url: ${SETTING_DB_URL:jdbc:postgresql://localhost:5432/resto?currentSchema=resto_setting}
    username: ${SETTING_DB_USERNAME:postgres}
    password: ${SETTING_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:validate}
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  messages:
    basename: messages,i18n/messages

server:
  port: ${SETTING_SERVER_PORT:8111}
  servlet:
    context-path: /api/setting-ms

service:
  organization:
    url: ${ORGANIZATION_SERVICE_URL:http://localhost:8102}

logging:
  level:
    az.flowix.setting: DEBUG


security:
  internal-auth:
    secret: ${INTERNAL_AUTH_SECRET}
