common:
  error:
    service-key: WAITER_MS

spring:
  application:
    name: waiter-service

  messages:
    basename: messages

server:
  port: ${WAITER_SERVER_PORT:8109}
  servlet:
    context-path: /api/waiter-ms

logging:
  level:
    az.codlab.waiter: DEBUG
