spring:
  main:
    web-application-type: none

  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
    enabled: true

logging:
  level:
    root: INFO
    liquibase: INFO
    liquibase.changelog: INFO
